apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: demo-danweb

images:
- name: williambr2022/demo-agenda-front
  newName: williambr2022/demo-agenda-front
  newTag: 2583011dd350db7402124e2447a69c26f08068d1
