export enum routes {
  DASHBOARD = '/dashboard',
  TYPOGRAPHY = '/typography',
  TABLES = '/tables',
  NOTIFICATION = '/notification',
  UI_ELEMENTS_ICONS = '/ui/icons',
  UI_ELEMENTS_CHARTS = '/ui/charts',
  UI_ELEMENTS_MAP = '/ui/map',
  EQUIPAMENTS_SPECIFICATIONS = '/especificacoes',
  EQUIPAMENTS = '/equipamentos',
  SCHEDULES = '/agendamentos',
  AVAILABILITY = '/disponibilidade',
  LOGIN = '/login',
  PEOPLE = '/pessoas',
  CLIENTS = '/clientes',
  CALENDAR = '/agenda',
  USER = '/usuario',
  USERS = '/usuarios',
  CONTRACTS = '/gerar-contratos',
  CONTRACTS_ANUAL = '/gerar-contratos-anual',
  MODEL_CONFIGURATION = '/configuracao-modelo',
  CONSUMABLES = '/consumiveis',
  CALENDAR_CONSUMABLE = '/lancar-consumiveis',
  CLIENT_EQUIPMENT = '/equipamentos-cliente',
  BULK_SCHEDULING = '/agenda-em-lote',
  INVOICING = '/faturamento',
  PRICE_TABLE = '/tabela-preco',
  NOTIFICACAO = '/notificacao',
  VISUALIZACAO = '/visualizacao',

}
